### ISSUE TITLE
What happened to the ocp311 playbook?

### ISSUE THREAD

**Issue by tjmcmanus** [ibm-cloud-architecture/cloudpak8s#100]

**Comment by dthiesse** [comment]
@tjmcmanus It should be up at ocp311.cloudpak8s.io . I will check it out and update the issue when it is resolved.

**Comment by dthiesse** [comment]
@gangchen03 assigning this issue to you. The ocp311.cloudpak8s.io site appears to be down. You can see a "raw" front page, but none of the links work. I am not an administrator of that repo, so I hope you can get it up and running again, or make me an admin.

**Comment by dthiesse** [comment]
Fixed. [https://ocp311.cloudpak8s.io](https://ocp311.cloudpak8s.io) is up and running again.
