### ISSUE TITLE
Update VMWare online install for OCP 4.3 for CP4I v2020.1.1

### ISSUE THREAD

**Issue by drmiller4** [ibm-cloud-architecture/cloudpak8s#108]
I ran thru the VMWare online install for ICP4I and installed tracing and API Connect. Some notes for the updates needed.

Get your entitlement key at: https://myibm.ibm.com/products-services/containerlibrary
Save the key as you will need it in subsequent steps.

Do a docker load: Note filename needs changed for v2020.1.1

sudo docker load -i installer_files/cluster/images/icp-inception-3.2.4.tgz

Edit the config.yaml file

Uncomment and specify admin password. Uncomment and specify password rules. Add 3 IP addresses. Specify default storage class. Specify entitlement key for docker password
Get block storage class using oc get sc. 

Sample areas of the config.yaml that you need to modify below:
`
cluster_nodes:
  master:
    - 10.94.72.130
  proxy:
    - 10.94.72.131
  management:
    - 10.94.72.131

storage_class: ibmc-block-gold

docker_username: cp
docker_password: entitlement-key that you retrieve from the Web site above
default_admin_password: admin
password_rules:
    - '(.*)'
`

Run online installer - note name has changed for v2020.1.1
sudo docker run -t --net=host -e LICENSE=accept -v $(pwd):/installer/cluster:z -v /var/run:/var/run:z -v /etc/docker:/etc/docker:z --security-opt label:disable ibmcom/icp-inception-amd64:3.2.4 addon -vvv | tee install.log

After install is done, note and save dashboard URL that is displayed.

`PLAY RECAP *********************************************************************
localhost                  : ok=390  changed=256  unreachable=0    failed=0   

POST DEPLOY MESSAGE ************************************************************

The Dashboard URL: https://icp-console.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud:443, please use credentials in config.yaml to login.

Playbook run took 0 days, 0 hours, 37 minutes, 14 seconds
`

Save the platform navigator host by doing the following:

echo "https://$(kubectl get route ibm-icp4i-prod -n integration -o jsonpath="{.spec.host}")"

https://ibm-icp4i-prod-integration.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

Project/namespaces are all there so you do NOT NEED to do the following command:
oc create -f <scriptname>.yaml

DOCKER_REGISTRY_USER environment variable needs to be cp

export DOCKER_REGISTRY_USER=cp
export DOCKER_REGISTRY_PASS=<your entitlement key>

Create the secrets. For the online install, this will create the secret: ibm-entitlement-key in all the Cloud Pak for Integration projects (namespaces)
run ./create-secrets.sh 

Save the proxy host by performing the following:
oc get configmap -n kube-public ibmcloud-cluster-info -o=jsonpath="{.data.proxy_address}"

icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

### Tracing Section
You do not need to create tracing project

### HELM Chart changes 

New management endpoints need to be specified
`Save URLs to use

Mgmt

mgmt.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

New endpoints for management

Platform API endpoint

mapi.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

Consumer API endpoint

mc.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

Cloud Admin UI endpoint

mca.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

Gateway API

gw.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

Gateway Service

gwd.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

Analytics ingestion

ai.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

Analytics client

ac.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

Portal Web

portal.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud

Portal Director

padmin.icp-proxy.drmicp4ios43cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud
`
No routing type parameter anymore

There is a section to create an optional additional gateway and tracing for that gateway. You can ignore as needed.

### API Connect Cloud Configuration
Configure smtp in Cloud Manager

If you get the following error: 

> A Server Error occurred. Notifications cannot be sent because the email_sender name and address are not configured in the cloud settings.

Make sure you configure sender email first before configuring the smtp server in the 
Sender & Email Server section for the Configure Cloud->Notification settings

When creating the provider org, Common Services User Registry should be selected, button no longer says IBM Cloud Private

Healthy List of API Connect pods at the end:
`oc get pods
NAME                                                         READY     STATUS      RESTARTS   AGE
apic1-apiconnect-operator-0                                  1/1       Running     0          84m
apic1-register-oidc-1-kccs9                                  0/1       Completed   0          84m
r09aaff73f9-analytics-proxy-7984f4cdd-55sph                  1/1       Running     0          79m
r09aaff73f9-apiconnect-cc-0                                  1/1       Running     1          79m
r09aaff73f9-apiconnect-cc-1                                  1/1       Running     1          76m
r09aaff73f9-apiconnect-cc-2                                  1/1       Running     0          71m
r09aaff73f9-apim-schema-init-job-fvn6k                       0/1       Completed   0          79m
r09aaff73f9-apim-v2-649ddbbd8f-shv5f                         1/1       Running     3          79m
r09aaff73f9-client-dl-srv-6c8fcd7856-7xfgh                   1/1       Running     0          79m
r09aaff73f9-juhu-865f46fb7-qwkqp                             1/1       Running     0          79m
r09aaff73f9-ldap-5784446db8-gzb9j                            1/1       Running     0          79m
r09aaff73f9-lur-schema-init-job-zmvb2                        0/1       Completed   0          79m
r09aaff73f9-lur-v2-5986f7dff7-8bhjp                          1/1       Running     1          79m
r09aaff73f9-ui-7f6896f6d8-4zzvp                              1/1       Running     0          79m
r307b84ffe1-analytics-client-7f4dbbbf4d-cc29x                1/1       Running     0          29m
r307b84ffe1-analytics-cronjobs-rollover-1586470500-6sj92     0/1       Completed   0          12m
r307b84ffe1-analytics-ingestion-5944f6d5-8fdmj               1/1       Running     0          29m
r307b84ffe1-analytics-mtls-gw-78456d4f65-zhw7t               1/1       Running     0          29m
r307b84ffe1-analytics-operator-5f7b6d858b-h7pcj              1/1       Running     0          29m
r307b84ffe1-analytics-storage-coordinating-f9db4d5b6-fc7t5   1/1       Running     0          29m
r307b84ffe1-analytics-storage-data-0                         1/1       Running     0          29m
r307b84ffe1-analytics-storage-master-0                       1/1       Running     0          29m
r9a3cf2a2d0-cassandra-operator-9865464d4-gtlxl               1/1       Running     0          79m
rbcb357bd8b-apic-portal-db-0                                 2/2       Running     0          37m
rbcb357bd8b-apic-portal-nginx-7b6b698b4f-ctlfp               1/1       Running     0          37m
rbcb357bd8b-apic-portal-www-0                                2/2       Running     0          37m
rf9ad2183d2-datapower-monitor-5fdff7f6bb-v5j7x               1/1       Running     0          25m
rf9ad2183d2-dynamic-gateway-service-0                        3/3       Running     0          25m
rf9ad2183d2-icp4i-od-registration-job-pf4ll                  0/1       Completed   0          25m

`

**Comment by dthiesse** [comment]
Hello @drmiller4 . The CP4I section was just updated for 2020.1.1 yesterday. Could you look thru the updated online install section and see if all your suggestions have been satisfactorily addressed? If so you can close the issue and if not, comment to identify what is still wrong and I will pursue it. Thanks for your input.

**Comment by dthiesse** [comment]
Assigning @mrislam11378 this issue since he is one of the "shepherds" of the CP4I section. He can work with the author if necessary to resolve any outstanding problems.

**Comment by drmiller4** [comment]
I tried to take a look using the url https://ocp42.cloudpak8s.io/integration/deploy-integration/ but could not. Will look at the updated pages in Github instead.

**Comment by mrislam11378** [comment]
yeah some of the urls have changed.

**Comment by dthiesse** [comment]
Just look at it on the web site URL [https://ocp42.cloudpak8s.io](https://ocp42.cloudpak8s.io) and follow it from there. I haven't found a broken link yet.

**Comment by drmiller4** [comment]
The online install/Non-ROKS looks very good. I like the way it is organized. Will the API Connect section be updated soon? Existing customers can also download from Fix Central in case there is a newer fixpack out than what Passport Advantage has.

**Comment by dthiesse** [comment]
Thanks @drmiller4 . @mrislam11378 can you answer or ask around about the API Connect section? I can add a sentence about what you said about downloading from Fix Central for the latest, which I think is valuable.

**Comment by mrislam11378** [comment]
Yeah I've been having problems with deploying APIC as well.

**Comment by drmiller4** [comment]
I had no issue with APIC and there are just a few changes we need. Mainly there are 3 new management endpoints URLs to specify in the HELM chart No longer a routing type param in the Helm chart and finally, an optional additional DataPower gateway instance you can configure. The post config for APIC requires an email address to be specified for the admin user.

**Comment by dthiesse** [comment]
Thanks @drmiller4 . @jabbott7335  did the latest section update on CP4I. Thanks John. Looking at this discussion on API Connect, do you have anything ready or close to ready to update that section? If not, maybe @drmiller4 can do a PR or just provide me the text to do the update myself.

**Comment by jabbott7335** [comment]
I can prioritize the APIC section for the next week or two.  We really want to do just enough to get us through to v10 that in my estimation will be extremely hot when it hits.

**Comment by dthiesse** [comment]
Perfect. Thanks @jabbott7335

**Comment by drmiller4** [comment]
@jabbott7335 @dthiesse Can we update the API Connect portion of the doc? ```

Parameter | Sample Value
-- | --
API Manager UI endpoint | mgmt.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
Cloud Admin UI endpoint | mcadmin.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
Platform API endpoint | mpapi.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
Consumer API endpoint | mcapi.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
API Gateway | gw.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
Gateway Service | gwd.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
Analytics Client | ac.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
Analytics Ingestion | ai.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
Portal | portal.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
Portal Director | padmin.icp-proxy.icp4i-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud

**Comment by alley28** [comment]
These URLs are going to differ by cluster as its based on the icp-proxy route as defined in the kube-system namespace.

**Comment by drmiller4** [comment]
Please remove this command from the asset repository instance config: oc adm policy add-scc-to-group anyuid system:serviceaccounts:&lt;namespace&gt;

This causes an issues with the database pod coming up and is no needed in v2020.1.1

**Comment by drmiller4** [comment]
For Event Streams in v2020.1.1, please add that you need to provide a Linux Group ID in the Helm Chart or you will see a permissions error for one of the pods. Go into the Helm chart and configure a Group ID of 1000

**Comment by dthiesse** [comment]
@drmiller4 and @jabbott7335 , I'm trying to clear off some of these long standing issues, so I will take a crack at adding what you have suggested in the last 2 days to the APIC and Event Streams sections. Since I am not experienced with CP4I, I will request your review on the PR when I get done.
