### ISSUE TITLE
missing content on terraform page?

### ISSUE THREAD

**Issue by csantanapr** [ibm-cloud-architecture/cloudpak8s#125]
On the following page https://ocp42.cloudpak8s.io/ocp/terraform/

The following text is at the bottom
```

 {% include_relative terraform_modules.md %}

```

**Comment by dthiesse** [comment]
@csantanapr I took the opportunity while fixing the terraform page to update the whole OpenShift platform section. Expanded description of OpenShift installation, made the platform sections more consistent, and included terraform examples. Will request your review of the PR.
