### ISSUE TITLE
link points to internal garage page not accessible

### ISSUE THREAD

**Issue by tcskill** [ibm-cloud-architecture/cloudpak8s#162]
instructions for MCM / Cloud Forms install and configure of LDAP point to an internal link not accessible externally.   The page here. 
https://cloudpak8s.io/mcm/cp4mcm_cloudforms/#configure-ldap-authentication-in-mcm-console

points "Deploy and Configure LDAP"  which is an internal garage site and not accesible.

**Comment by jdiggity22** [comment]
We should probably just remove this link.

**Comment by jdiggity22** [comment]
I update the link to https://www.ibm.com/support/knowledgecenter/en/SSFC4F_1.3.0/iam/3.4.0/configure_ldap.html and will submit PR.

**Comment by jdiggity22** [comment]
Fixed in this PR: https://github.com/ibm-cloud-architecture/cloudpak8s/pull/185
