### ISSUE TITLE
Online MCM install: The command to create a kubeconfig file is incorrect

### ISSUE THREAD

**Issue by nickfreer** [ibm-cloud-architecture/cloudpak8s#177]
On the page https://cloudpak8s.io/mcm/cp4mcm_mcm_install/#online-installation 
 In the online installation section, step 7 says: 'oc config view > cluster/kubeconfig'. This should be 'oc config view --raw > cluster/kubeconfig'
( the --raw flag is required otherwise the certificate info is not included in the file).

NOTE: this is specified correctly in the offline installation section 6

**Comment by jdiggity22** [comment]
Thanks Nick.. I will update.

**Comment by jdiggity22** [comment]
Should be fixed in this PR. https://github.com/ibm-cloud-architecture/cloudpak8s/pull/183
