### ISSUE TITLE
cannot open cloudpak for integration

### ISSUE THREAD

**Issue by alanchivers** [ibm-cloud-architecture/cloudpak8s#189]
Hi when i try and open the cloudpak for integration , I get a 404 message . This only occurs when i go through https://cloudpak8s.io/  and then click on the integration icon https://cloudpak8s.io/integration/introduction/,  the other cloudpaks links work  fine,  I also tried it on a different machine same issue. Here is the error message. 
https://user-images.githubusercontent.com/67660323/88545531-054b5300-d013-11ea-8e8d-6523be53ac1f.png

I also checked the github page https://github.com/ibm-cloud-architecture/cloudpak8s and 
and clicked  The live site can be viewed here: https://cloudpak8s.io/

I then tried it a different route using https://cloudpak8s.io/integration/cp4i-introduction/ which seemed to work ok 
but then i noticed the heading..had a minor but glaring error!
Version 2020.2 is out for Cloud Pak for Ingegration. This version is the first to feature Operators and has significant changes to the deployment and operations. Please refer to the Knowledge Center while we update this playbook. Thanks!

**Comment by jdiggity22** [comment]
@alanchivers , my guess is that someone re-named the introduction page and that broke the link. Thanks for bringing that to our attention. We will get it fixed.

**Comment by jabbott7335** [comment]
submitted PR to fix both of these
