### ISSUE TITLE
Numbering incorrect on contribute page

### ISSUE THREAD

**Issue by doormat18** [ibm-cloud-architecture/cloudpak8s#196]
On the contributing page, in the section for the Git flow, the instruction numbering starts with 4 instead of 1.

https://cloudpak8s.io/contribute/

**Comment by jdiggity22** [comment]
Yeah.. This is strange. I think it maybe browser specific. I checked it with Chrome and it looked fine. In Firefox I see it starting a 4. I will take a look. Thanks for bringing this to our attention.

**Comment by doormat18** [comment]
Seems to be a more pervasive issue on Firefox. The common services page numbering starts at 2. instead of 1. on Firefox.

**Comment by dthiesse** [comment]
I'm working this issue. I have also verified that this issue only exists for the Firefox browser. Numbering behavior is correct in Chrome and Safari. This problem just appeared recently so could be related to some new plugins I added to fix a different problem. Still working on it.
