### ISSUE TITLE
CP4Data installation instructions out of date

### ISSUE THREAD

**Issue by guywilliamson** [ibm-cloud-architecture/cloudpak8s#216]
The instructions need to be updated for CP4Data 3.5: https://cloudpak8s.io/data/installation/
Also, I notice that the links to details return 404

**Comment by dthiesse** [comment]
Hi @guywilliamson . I think you will find that the installation instructions for all of the Cloud Paks are now out of date. Our leadership has come to a collective decision that we are no longer able to keep this site up to date, given our other responsibilities. We are redirecting our efforts to contributing to and improving the official Knowledge Center documentation, in this case, https://www.ibm.com/support/knowledgecenter/en/SSQNUZ_3.5.0/cpd/overview/welcome.html. The Cloud Pak Playbook site will soon have installation-oriented content removed and we are working on migrating cross Cloud Pak content to other public sites.
