### ISSUE TITLE
Cloud Pak for Integration: Wrong initial user / password

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/cloudpak8s#3]
In the section https://cloudpak8s.io/integration/deploy-api-mgmt/#configuring-the-api-connect, it says to use my ICP user / password. 

However, according to the KC page https://www.ibm.com/support/knowledgecenter/en/SSMNED_2018/com.ibm.apic.cmc.doc/login.html, I am supposed to use 7iron-hide as the initial password.

**Comment by alley28** [comment]
This is not correct for the Cloud Pak for Integration when using the Common Services registry for a provider organization.  See here:  https://www.ibm.com/support/knowledgecenter/SSGT7J_19.4/install/install_api.html
