### ISSUE TITLE
ICP4I documentation improvements for enabling apic tracing with operations dashboard

### ISSUE THREAD

**Issue by drmiller4** [ibm-cloud-architecture/cloudpak8s#47]
In the ICP4I integration playbook, before the section Configure APIC to work with Tracing section, please add a note that you should not enable the v5 Compatible gateway for the APIC sandbox catalog in order for API calls to be traced. Refer to
https://www.ibm.com/support/knowledgecenter/SSGT7J_19.4/install/od_register.html
Only APIs using the API Gateway (not the v5 Compatible Gateway) will deliver data to the Operations Dashboard. Also, also add a note to be sure check the box to Enable the Operations Dashboard tracing in the Helm chart. Once OD tracing is enabled, you will need to complete the steps in the Configure APIC to work with Tracing section in order for the APIC od-registration-job to complete.

**Comment by alley28** [comment]
fixed.  Also fixed a documentation and screen shot and were contradictory
