### ISSUE TITLE
ICP4I documentation improvements for apic setup of developer portal

### ISSUE THREAD

**Issue by drmiller4** [ibm-cloud-architecture/cloudpak8s#48]
If you get the following error when trying to create a developer portal for the sandbox catalog then edit the profile for the admin user in the API Manager and enter a valid email address in the email address field. You need to assign email address with catalog owner – admin.

An error occurred communicating with the portal service at 'https://padmin.icp-proxy.drm-cp4i-cluster-bd61e41b2ca9182e95120f4f372e19d6-0001.us-south.containers.appdomain.cloud' (status: 400, response: '"Failed to process the portal service configuration request. Missing required property 'admin_email' in request body"').
500 API Error

**Comment by alley28** [comment]
fixed for next pull request
