### ISSUE TITLE
ICP4I documentation improvements for setup of smtp server in apic Cloud Manager

### ISSUE THREAD

**Issue by drmiller4** [ibm-cloud-architecture/cloudpak8s#49]
A quick and easy setup for an smtp server required by API Connect is to use MailTrap.io. Go to https://mailtrap.io and set yourself an account. I believe you are limited to 500 emails per month for free. See pricing plans at https://mailtrap.io/pricing. Once you reach the monthly limit, you'll get the SMTP protocol error: "535 5.7.

Some key info you need in order to setup the smtp resource in the APIC Cloud are smtp server address. port number, username, and password.

Once setup with MailTrap.io, clink on your inbox link  in MailTrap and copy the username and password from the credentials section into the APIC username and password fields.

You will see something similar below in the credentials section in MailTrap:

config.action_mailer.smtp_settings = {
  :user_name => 'xxxxxxxxxxxxx',
  :password => 'xxxxxxxxxxxxxx',
  :address => 'smtp.mailtrap.io',
  :domain => 'smtp.mailtrap.io',
  :port => '2525',
  :authentication => :cram_md5address: smtp.mailtrap.io

address and port can also be take directly from the credentials section.

address: smtp.mailtrap.io
port: 2525
username: xxxxxxxxxxxxx
password:   xxxxxxxxxxxx

Click the Test button in the APIC Cloud Manager and your email will be successfully sent and you can view it in MailTrap.io

**Comment by alley28** [comment]
fixed for next push
