### ISSUE TITLE
ICP4I increments number in offering dashboard link if existing cp4i workspace is present

### ISSUE THREAD

**Issue by drmiller4** [ibm-cloud-architecture/cloudpak8s#50]
In order to avoid issues with accessing the cp4i platform dashboard, be sure to delete any old cp4i workspaces you no longer need or be sure to use a unique name for your project when provisioning a new Cloud Pak for Integration instance. If you have an existing cp4i workspace and then subsequently provision a new cp4i workspace, the URL link on the Offering Dashboard will be incorrect. For example the 0000 before .us-south is wrong in the following URL. Instead the 0000 needs replaced with 0001: 

**Incorrect URL**: https://integration-integration.drm-cp4i-cluster-bd61e41b2ca9182e95120f4f372e19d6-0000.us-south.containers.appdomain.cloud/

**Correct URL:** https://integration-integration.drm-cp4i-cluster-bd61e41b2ca9182e95120f4f372e19d6-0001.us-south.containers.appdomain.cloud/ 

To delete an old workspace instance, in the IBM Cloud navigate to Schematics->Workspaces and delete the old workspace. Do not delete the underlying OpenShift cluster first or you will have to open a support ticket to delete your workspace as it will error out if the underlying cluster is gone.

**Comment by alley28** [comment]
for the ROKS documentation, I've created a Helpful Hints section here where folks can add tips and tricks for create CP4I instance on ROKS.  Change made and ready for push
