### ISSUE TITLE
ICP4I documentation improvement for ACE component - persistent volume claim

### ISSUE THREAD

**Issue by drmiller4** [ibm-cloud-architecture/cloudpak8s#51]
Leave the Persistent Volume Claim field blank. The HELM release will generate one for you. If you use an existing claim in use already, your container(s) will not start up in the pod. In the storage class field, enter a file based storage such as ibmc-file-gold or ibmc-file-bronze.

**Comment by alley28** [comment]
Fixed for latest pull release
