### ISSUE TITLE
ICP4I documentation improve for apic component - list pods

### ISSUE THREAD

**Issue by drmiller4** [ibm-cloud-architecture/cloudpak8s#52]
Update this section towards the end to show a healthy list of pods such as this:
The list of pods should look similar to this one: ``

apic-ibm-apiconnect-icp4i-prod-operator-0                     1/1       Running     1          2h
r09aaff73f9-analytics-proxy-5c95c649d9-2ld22                  1/1       Running     0          2h
r09aaff73f9-apiconnect-cc-0                                   1/1       Running     0          4h
r09aaff73f9-apiconnect-cc-1                                   1/1       Running     0          3h
r09aaff73f9-apiconnect-cc-2                                   1/1       Running     0          2h
r09aaff73f9-apiconnect-cc-repair-1582765200-b5964             0/1       Completed   0          2h
r09aaff73f9-apim-v2-857cd65d49-2mpsc                          1/1       Running     0          2h
r09aaff73f9-client-dl-srv-5c74686597-j5rmw                    1/1       Running     0          2h
r09aaff73f9-juhu-b995789c-c7glf                               1/1       Running     0          2h
r09aaff73f9-ldap-6656df9f7-cfv49                              1/1       Running     0          2h
r09aaff73f9-lur-v2-5ddddcfc77-r2k74                           1/1       Running     0          2h
r09aaff73f9-ui-6dbcf69d48-qhwtk                               1/1       Running     0          2h
r307b84ffe1-analytics-client-5758786cf8-k484c                 1/1       Running     0          2h
r307b84ffe1-analytics-cronjobs-retention-1582767000-dnmvk     0/1       Completed   0          1h
r307b84ffe1-analytics-cronjobs-rollover-1582771500-gzh7w      0/1       Completed   0          15m
r307b84ffe1-analytics-ingestion-6d9dd9c977-5rhx2              1/1       Running     0          2h
r307b84ffe1-analytics-mtls-gw-7c9fbbbfcd-pmdzq                1/1       Running     0          2h
r307b84ffe1-analytics-operator-785bf8c8c9-n6nxs               1/1       Running     0          2h
r307b84ffe1-analytics-storage-coordinating-5d596f596b-hd7v4   1/1       Running     0          2h
r307b84ffe1-analytics-storage-data-0                          1/1       Running     0          2h
r307b84ffe1-analytics-storage-master-0                        1/1       Running     0          3h
r9a3cf2a2d0-cassandra-operator-54c75c5c6f-mvfd2               1/1       Running     0          2h
rbcb357bd8b-apic-portal-db-0                                  2/2       Running     0          4h
rbcb357bd8b-apic-portal-nginx-6d5b5f9d5c-bbczb                1/1       Running     0          2h
rbcb357bd8b-apic-portal-www-0                                 2/2       Running     0          4h
rf9ad2183d2-datapower-monitor-5c4cb7d895-zjxc2                1/1       Running     0          2h
rf9ad2183d2-dynamic-gateway-service-0                         3/3       Running     0          3h

**Comment by alley28** [comment]
added list of pods above to document to show what a good deployment looks like.  Prepped for next pull request.
