### ISSUE TITLE
Broken Image Links for Cloud Pak for Integration

### ISSUE THREAD

**Issue by danchirillo** [ibm-cloud-architecture/cloudpak8s#59]
In [Create the TLS Secret](https://ocp42.cloudpak8s.io/integration/deploy-api-mgmt/#create-the-tls-secret) section.

**Comment by Sandvich** [comment]
It looks like all of the images that are using relative links are broken. The few working images I see are using a "/assets" url.

**Comment by csantanapr** [comment]
Pages with broken images
https://ocp42.cloudpak8s.io/integration/deploy-api-mgmt/
https://ocp42.cloudpak8s.io/integration/deploy-asset-repo/
https://ocp42.cloudpak8s.io/integration/deploy-eventstreams/
https://ocp42.cloudpak8s.io/integration/deploy-integration/
https://ocp42.cloudpak8s.io/integration/deploy-tracing/
https://ocp42.cloudpak8s.io/integration/deploy-queue-manager/
