### ISSUE TITLE
Problems with Integration page after PR

### ISSUE THREAD

**Issue by dthiesse** [ibm-cloud-architecture/cloudpak8s#76]
After merging your PR, I noticed a few small problems:
1. There is still a w3 link here. If you need to include it, maybe you can add a little notice before-hand saying "This section is only for IBM employees" or something similar.
![image](https://user-images.githubusercontent.com/24577229/77017468-96fdd200-6948-11ea-8154-62aff01c4012.png)

2. I think you meant to create a hyperlink here to the file, rather than put the full path in. You can find other examples of links to screen shot images, etc in the source files. Since you have a working link to the config.yaml file further down, you can just copy that one.
![image](https://user-images.githubusercontent.com/24577229/77017679-0e336600-6949-11ea-82e2-d4f6ff6d7f03.png)
Here's that working example on the same page.
![image](https://user-images.githubusercontent.com/24577229/77017737-391dba00-6949-11ea-8db3-49e8e51fa209.png)

**Comment by mrislam11378** [comment]
Okay
1.  Yup, I totally missed that.

 2. This is intentional and not an error. It's just a path to where the file is located in the install node. #1

**Comment by dthiesse** [comment]
Gotcha. Thanks @mrislam11378 . Guess I leaped to a conclusion on 2. Thanks for the clarification.
