### ISSUE TITLE
CP4MCM install wrong entitlement key user

### ISSUE THREAD

**Issue by hsternkicker** [ibm-cloud-architecture/cloudpak8s#77]
I tried the online installation of the CP4 MCM. The documentation here uses ekey as the user name for the docker login. Which seems to be correct as docker login succeeds. But after that the docker pull command fails with "no pull access" error.
MCM Installation documentation uses the cp user instead. With that user name docker login and docker pull works.
Exchange in the commands ekey with cp !

**Comment by jdiggity22** [comment]
Thanks..The "ekey" user was an internal user ID that we used for testing. The reference was missed in review. Thanks for the update. It should be fixed now.
