### ISSUE TITLE
MCM Governance and Risk page has link to CSP Lab server

### ISSUE THREAD

**Issue by slipsibm** [ibm-cloud-architecture/cloudpak8s#83]
There is a hot link on the MCM - Governance and Risk Page that points to https://icp-console.apps.res-cp4mcm.ocp.csplab.local/multicloud/policies/create

This page should probably just say. "Go to your MCM Console and select the Governance and Risk Option" or something like that....

**Comment by jdiggity22** [comment]
Your are right.. I will get that updated. Thanks!
