### ISSUE TITLE
DataPower Component config

### ISSUE THREAD

**Issue by drmiller4** [ibm-cloud-architecture/cloudpak8s#86]
At the end show how to access the Web UI interface if enabled:
kubectl port-forward <datapower-pod-name> 9443:9090

Access the DataPower Web GUI using the local port number (9443 in this case)
https://localhost:9443
Username: admin
Password: admin

**Comment by dthiesse** [comment]
@mrislam11378 would you give this issue some consideration?

**Comment by mrislam11378** [comment]
Yeah actually I'll assign it to the datapower squad from CPAT
