### ISSUE TITLE
include instructions to contribute to markdown in README

### ISSUE THREAD

**Issue by asimasiddiqui** [ibm-cloud-architecture/cloudpak8s#88]
Please provide instruction on how to update existing markdown or contribute new using pr's.

Thanks!

**Comment by asimasiddiqui** [comment]
Right now it shows instructions that were for previous jekyll gitpages site.

**Comment by dthiesse** [comment]
Hello @asimasiddiqui . The contribution guide is here https://ocp42.cloudpak8s.io/contribute/, linked from the left navigation bar. I'll close the issue for now, but if you have any suggestions on how to make it more visible, please reopen. Thanks!
